[versions]
agp = "8.13.0"
maven-publish = "0.34.0"

dexfile = "v1.2.1"
raung = "v1.0.0"
r8-annotations = "v1.0.0"
sun-cleaner = "v1.0.0"
sun-unsafe = "v1.0.0"

[libraries]
dexfile = { module = "io.github.vova7878:DexFile", version.ref = "dexfile" }
r8-annotations = { module = "io.github.vova7878:R8Annotations", version.ref = "r8-annotations" }
sun-cleaner = { module = "io.github.vova7878:SunCleanerStub", version.ref = "sun-cleaner" }
sun-unsafe = { module = "io.github.vova7878:SunUnsafeWrapper", version.ref = "sun-unsafe" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }

raung = { id = "io.github.vova7878.RaungPlugin", version.ref = "raung" }
